version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  lint_code:
    executor: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

  unit_tests:
    executor: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm test || echo "No unit tests configured"

  e2e_tests:
    docker:
      - image: cypress/included:12.17.1
    steps:
      - checkout
      - run: npm install --legacy-peer-deps
      - run:
          name: Start Vite dev server
          command: npm run dev -- --host 0.0.0.0 --port 5173
          background: true
      - run:
          name: Run Cypress tests
          command: npm run test:2e2

  build_docker_image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t sha1727/featureflags-frontend:latest .
      - run:
          name: Push to DockerHub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker push sha1727/featureflags-frontend:latest

  notify:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Pipeline completado correctamente"

workflows:
  version: 2

  full_pipeline:
    jobs:
      - lint_code
      - unit_tests:
          requires:
            - lint_code
      - e2e_tests:
          requires:
            - unit_tests
      - build_docker_image:
          requires:
            - e2e_tests
      - notify:
          requires:
            - build_docker_image
