version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  lint_code:
    executor: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

  unit_tests:
    executor: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm test || echo "No unit tests configured"

  test_ci:
    executor: node/default
    steps:
      - checkout
      - run: npm ci
      - run: npm run test:ci

  build_docker_image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t sha1727/featureflags-frontend:latest .
      - run:
          name: Push to DockerHub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker push sha1727/featureflags-frontend:latest

  notify:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Pipeline completado correctamente"

workflows:
  version: 2
  full_pipeline:
    jobs:
      - lint_code
      - unit_tests:
          requires:
            - lint_code
      - test_ci:
          requires:
            - unit_tests
      - build_docker_image:
          requires:
            - test_ci
      - notify:
          requires:
            - build_docker_image
